Repository datacarpentry/sql-ecology-lesson, pull requests merged in 2020-08, with the labels that each got.

#207 Wording aggregation lesson
  _episodes/02-sql-aggregation.md
Labels: type:clarification

#217 Reindented solutions so list items increment correctly
  _episodes/03-sql-joins.md
Labels: type:bug, type:formatting

#221 update Introduction to match DB Browser for SQLite
  _episodes/00-sql-introduction.md
Labels: type:bug

#249 Change order of first three queries
  _episodes/01-sql-basic-queries.md
Labels: type:clarification

#251 Update 03-sql-joins.md
  _episodes/03-sql-joins.md
Labels: type:enhancement
